"""
common.py — SHIM. Do not edit this file.

The real common.py for the apple-mail toolkit lives at:
    ~/.claude/skills/apple-mail-toolkit/scripts/apple_mail_common.py

This shim exists so each skill's scripts can keep doing `from common import ...`
without knowing where the canonical module lives. Editing the canonical updates
every skill at once — no copy/paste drift across 7 skill directories.

If you need to change shared helpers (escape_applescript, run_applescript,
load_profile, load_workspace_voice_overlay, etc.), edit the canonical, not this
file.
"""

import sys as _sys
from pathlib import Path as _Path

_TOOLKIT_SCRIPTS = _Path.home() / ".claude" / "skills" / "apple-mail-toolkit" / "scripts"
_toolkit_str = str(_TOOLKIT_SCRIPTS)
if _toolkit_str not in _sys.path:
    _sys.path.insert(0, _toolkit_str)

# Re-export everything from the canonical module so `from common import X` works.
from apple_mail_common import *  # noqa: F401,F403,E402
